import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/src/components/ui/sonner";
import { Suspense } from "react";
import QueryProvider from "@/src/providers/QueryProvider";
import NextTopLoader from "nextjs-toploader";
import Loading from "../components/shared/Loading";

const DmSans = DM_Sans({
  subsets: ["latin-ext"],
  variable: "--dm-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${DmSans.className} antialiased`}>
        <NextTopLoader color="#952800" showSpinner={false} />
        <Suspense fallback={<div></div>}>
          <QueryProvider>
            {children}

            <Toaster richColors position="top-right" closeButton />
          </QueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
