import { Payout } from "../types/admin-payout";

export const MOCK_PAYOUTS_DATA: Payout[] = [
  {
    id: "PAY-001",
    paymentMethod: "Paypal",
    affiliateName: "Sarah Johnson",
    affiliateEmail: "sarah@example.com",
    businessName: "John Smith",
    businessCategory: "Software Store",
    amount: "₦80,892",
    conversions: 15,
    status: "Paid",
    dateRequested: "Mar 15, 2025",
    timeAgo: "2 months ago",
  },
  {
    id: "PAY-002",
    affiliateName: "Emma Williams",
    affiliateEmail: "emma@example.com",
    businessName: "John Smith",
    businessCategory: "Software Store",
    amount: "₦80,892",
    conversions: 15,
    paymentMethod: "Paypal",
    status: "Pending",
    dateRequested: "Mar 15, 2025",
    timeAgo: "2 months ago",
  },
  {
    id: "PAY-003",
    affiliateName: "Mike Chen",
    affiliateEmail: "mike@example.com",
    businessName: "John Smith",
    paymentMethod: "Paypal",
    businessCategory: "Software Store",
    amount: "₦80,892",
    conversions: 15,
    status: "Pending",
    dateRequested: "Mar 15, 2025",
    timeAgo: "2 months ago",
  },
  {
    id: "PAY-004",
    affiliateName: "Sarah Johnson",
    affiliateEmail: "sarah@example.com",
    paymentMethod: "Paypal",
    businessName: "John Smith",
    businessCategory: "Software Store",
    amount: "₦80,892",
    conversions: 15,
    status: "Paid",
    dateRequested: "Mar 15, 2025",
    timeAgo: "2 months ago",
  },
  {
    id: "PAY-005",
    affiliateName: "Emma Williams",
    affiliateEmail: "emma@example.com",
    paymentMethod: "Paypal",
    businessName: "John Smith",
    businessCategory: "Software Store",
    amount: "₦80,892",
    conversions: 15,
    status: "Pending",
    dateRequested: "Mar 15, 2025",
    timeAgo: "2 months ago",
  },
  {
    id: "PAY-006",
    affiliateName: "Mike Chen",
    affiliateEmail: "mike@example.com",
    businessName: "John Smith",
    businessCategory: "Software Store",
    amount: "₦80,892",
    paymentMethod: "Paypal",
    conversions: 15,
    status: "Pending",
    dateRequested: "Mar 15, 2025",
    timeAgo: "2 months ago",
  },
  {
    id: "PAY-007",
    affiliateName: "Sarah Johnson",
    affiliateEmail: "sarah@example.com",
    businessName: "John Smith",
    businessCategory: "Software Store",
    paymentMethod: "Paypal",
    amount: "₦80,892",
    conversions: 15,
    status: "Failed",
    dateRequested: "Mar 15, 2025",
    timeAgo: "2 months ago",
  },
  {
    id: "PAY-008",
    affiliateName: "Emma Williams",
    affiliateEmail: "emma@example.com",
    paymentMethod: "Paypal",
    businessName: "John Smith",
    businessCategory: "Software Store",
    amount: "₦80,892",
    conversions: 15,
    status: "Paid",
    dateRequested: "Mar 15, 2025",
    timeAgo: "2 months ago",
  },
  {
    id: "PAY-009",
    affiliateName: "Mike Chen",
    affiliateEmail: "mike@example.com",
    businessName: "John Smith",
    businessCategory: "Software Store",
    paymentMethod: "Paypal",
    amount: "₦80,892",
    conversions: 15,
    status: "Paid",
    dateRequested: "Mar 15, 2025",
    timeAgo: "2 months ago",
  },
];

export const PAYOUT_STATUS_STYLES = {
  Paid: "bg-[#D1FAE5] text-[#065F46]",
  Pending: "bg-[#FEF3C7] text-[#92400E]",
  Failed: "bg-[#FEE2E2] text-[#991B1B]",
};
