#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Load NVM if available
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Run lint-staged to handle formatting and linting
npm run lint-staged